; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
build_flags = 
	-Ilib/aht20
	-Ilib/aht30
	-Ilib/bmp280
	-Wno-unused-function
lib_deps = 
	https://github.com/mkocot/arduino-crc8.git#1.0.3
	https://github.com/mkocot/aht20.git#feat/configurable-debug
	https://github.com/mkocot/aht30.git#feat/configurable-debug
	https://github.com/mkocot/bmp280.git#feat/configurable-debug

[env:LGT8F328P]
platform = lgt8f
board = LGT8F328P
board_build.f_cpu = 16000000L
framework = arduino
upload_port = /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0
monitor_port = ${this.upload_port}
platform_packages = 
	platformio/toolchain-atmelavr@file://${platformio.workspace_dir}/../../avr-gcc-13.2.0-x64-linux
	framework-lgt8fx
build_flags = 
	${env.build_flags}
	-I../avr-libstdcpp/include
lib_deps = 
	${env.lib_deps}
	arkhipenko/TaskScheduler@^3.7.0
	dejwk/roo_collections@^1.1.6
	chris--a/PrintEx @ ^1.2.0
	felias-fogg/FlexWire@^1.2.1
	sensirion/arduino-sht@^1.2.6
	ivanseidel/LinkedList@0.0.0-alpha+sha.dac3874d28
	adafruit/Adafruit MAX31865 library@^1.6.2
	adafruit/Adafruit BusIO@^1.16.2

[env:CH32V003]
platform = ch32v
board = genericCH32V003F4P6
framework = arduino
lib_deps = 
	${env.lib_deps}
	bitbank2/BitBang_I2C@^2.2.1
	arkhipenko/TaskScheduler@^3.7.0
	dejwk/roo_collections@^1.1.6
	felias-fogg/FlexWire@^1.2.1
	sensirion/arduino-sht@^1.2.6
	ivanseidel/LinkedList@0.0.0-alpha+sha.dac3874d28
	adafruit/Adafruit MAX31865 library@^1.6.2
	adafruit/Adafruit BusIO@^1.16.2
