; PlatformIO Project Configuration File
;
;   Build options: build flags, source filter
;   Upload options: custom upload port, speed and extra flags
;   Library options: dependencies, extra library storages
;   Advanced options: extra scripting
;
; Please visit documentation for the other options and examples
; https://docs.platformio.org/page/projectconf.html

[env]
build_flags = -Wno-unused-function
lib_deps = 
	file:///home/nfinity/git/arduino-crc8
	https://github.com/mkocot/aht20.git#feat/configurable-debug
	https://github.com/mkocot/aht30.git#feat/configurable-debug
	https://github.com/mkocot/bmp280.git#feat/configurable-debug

[env:LGT8F328P]
platform = lgt8f
board = LGT8F328P
board_build.f_cpu = 16000000L
framework = arduino
upload_port = /dev/serial/by-id/usb-1a86_USB_Serial-if00-port0
monitor_port = ${this.upload_port}
platform_packages = 
	platformio/toolchain-atmelavr@file://${platformio.workspace_dir}/../../avr-gcc-13.2.0-x64-linux
	framework-lgt8fx
build_flags = 
	${env.build_flags}
	-I../avr-libstdcpp/include
lib_deps = 
	${env.lib_deps}
	arkhipenko/TaskScheduler@^3.7.0
	dejwk/roo_collections@^1.1.6
	felias-fogg/FlexWire@^1.2.1
	sensirion/arduino-sht@^1.2.6
	ivanseidel/LinkedList@0.0.0-alpha+sha.dac3874d28
	adafruit/Adafruit MAX31865 library@^1.6.2
	adafruit/Adafruit BusIO@^1.16.2

[env:ch32v003]
board = genericCH32V003F4P6
platform = ch32v
framework = ch32v003fun
upload_protocol = minichlink
build_flags = 
	; -DCH32V003
	-DSDI_PRINT=1
	-DDRIVER_BMP280_WITH_INT
	-DFPT_WBITS=16
	-Werror=format
	-Werror=incompatible-pointer-types

[env:ch32v006]
platform = ch32v
board = genericCH32V006F8P6
framework = ch32v003fun
upload_protocol = minichlink
debug_init_break = tbreak
build_flags = 
	-DCH32V00x
	-DSDI_PRINT=1
	; -DDRIVER_BMP280_WITH_INT
	-DFPT_WBITS=16
	-DFR_CORE_ONLY=1
	-Wall
	-Wextra
	-Wshadow
	-Wundef ; annoying when kick in in system libraries
	-Wno-unused-parameter
	-Werror=undef
	-Werror=format
	-Werror=overflow
	-Werror=incompatible-pointer-types
	-Wno-unused-function ; for now annoying warning for any library function
	-fno-common
	; -Wconversion
	; -Wsign-conversion
	; debug flags
	-Wformat=2
	-Wformat-truncation
	; 944 25480
test_ignore = test_desktop

[env:native-test]
platform = native
test_ignore = test_embedded
; board = genericCH32V006F8P6
; framework = ch32v003fun
; upload_protocol = minichlink
; debug_init_break = tbreak
build_src_filter = +<arena.c>
test_build_src = yes
build_flags = 
	-DCH32V00x
	-DSDI_PRINT=1
	; -DDRIVER_BMP280_WITH_INT
	-DFPT_WBITS=16
	-Iinclude
	-Ilib/fptc-lib/src
	-Werror=format
	-Werror=overflow
	-Werror=incompatible-pointer-types
	; -Wconversion
	; -Werror=conversion
	; -Wsign-conversion

[env:ch32v006x]
platform = ch32v
board = genericCH32V006F8P6
framework = noneos-sdk
;upload_protocol = minichlink
upload_protocol = custom
upload_command = wlink flash $UPLOAD_FLAGS $SOURCE
upload_flags =   
monitor_speed = 921600
build_flags = 
	-DCH32V00x
	-DSDI_PRINT=1
	-DDRIVER_BMP280_WITH_INT
	-DFPT_WBITS=16
	-Werror=format
	-Werror=incompatible-pointer-types
#test_testing_command =
#    ${platformio.packages_dir}/tool-qemu-riscv/bin/qemu-system-riscv32
#    -nographic
#    -machine
#    sifive_e
#    -kernel
#    ${platformio.build_dir}/${this.__env__}/firmware.elf
